### ISSUE TITLE
keep console log Error

### ISSUE THREAD

**Issue by diadal** [mattias-persson/vue-axios-interceptors#1]
keep console log Error `Require vue-axios-interceptors after you require Vue.` and not working 

```
import Vue from 'vue';
require('vue-axios-interceptors');
```

**Comment by mattias-sanfridsson** [comment]
Hi @diadal! Could you provide some more details? How do I reproduce the issue, and what was the expected behavior?

Thanks!

**Comment by diadal** [comment]
I change `import Vue from 'vue';` to `window.Vue = require('vue');` issue fixed

**Comment by mattias-sanfridsson** [comment]
Awesome!
