### ISSUE TITLE
Import order

### ISSUE THREAD

**Issue by Noogic** [mattias-persson/vue-axios-interceptors#2]
In the documentation it says

> // Make sure you import this package after you've imported Vue:
>window.Vue = require('vue');
> 
>require('vue-axios-interceptors');
> 
>// Make sure the axios package is available globally on the window object:
>window.axios = require('axios');

That means importing interceptors before axios. This is not working for me. I've had to import first axios and then vue-axios-interceptors in order to make it work.

**Comment by mattias-sanfridsson** [comment]
Could you provide a sample of your code and describe the error you got when following the instructions?

**Comment by Noogic** [comment]
I'm sorry, I don't have it anymore, but it was the base script (index.js or app.js, the one you load in your main view in an SPA with vue)

```
import Vue from 'vue';
require('vue-axios-interceptors');
window.axios = require('axios');

const app = new Vue({
    el: "#app"
});
```

Something like that wasn't working. I had to require first axios and then axios-interceptors and then it worked.

**Comment by mattias-sanfridsson** [comment]
It could have something to do with not assigning Vue or axios to the window object. Glad you got it working though! I'll look over the docs when I can.
